### ISSUE TITLE
Is Bootstrap compatible with React.js and Router?

### ISSUE THREAD

**Issue by NikoLewis** [C4Q/AC3.1#86]
I'm able to use Bootstrap for buttons like Nate did in class, but when I attempt a more complex Bootstrap component ( like a Navbar), JSX no longer recognizes my closing tags and the app breaks (even though I've changed 'class' to 'className'). If I remove Router from my app, adding a Bootstrap Navbar doesn't break the app, but none of the Bootstrap styling is working. Any insight? After googling I keep seeing mention of a npm install called react-bootstrap, do we require this or something else to make this work?

**Comment by lizraeli** [comment]
Hi Niko, next time it would be easier to help if you provide a specific project, file, code snippets, etc. I assumed you were referring to this project:  [https://github.com/NikoLewis/Trinitea](url). 

I implemented a simple navbar inside the navbar.js file. Let me know if you have further questions, or if this isn't what you intended to do.

```
import {Link} from "react-router"
import React from "react"
import "bootstrap/dist/css/bootstrap.css";

var Navbar = React.createClass({
  render: function() {
    return (
   <div className="navbar navbar-default">
     <div className="container-fluid">
       <ul className="nav navbar-nav">
         <li className="active"><Link to='/'>Home</Link></li>
         <li><Link to='#'>bla</Link></li>
       </ul>
    </div>
  </div>

    )
  }
})

 export default Navbar
```

**Comment by Ceejaymar** [comment]
Seems like not all bootstrap classes work with React. React-Bootstrap doesn't work the same way as regular bootstrap. Although, I have not tried it.  I suggest doing what you can with bootstrap then apply custom styling on top of it.

**Comment by samanthabretous** [comment]
Use flexbox. Save your life.
